#!/bin/bash
echo "Searching for init_task in kallsyms..."
echo ""
echo "Try these commands:"
echo ""
echo "# Look for init_task data symbol (capital D or B):"
echo "sudo grep -E '^[0-9a-f]+ [DB] init_task' /proc/kallsyms"
echo ""
echo "# Or search more broadly:"
echo "sudo grep ' init_task$' /proc/kallsyms"
echo ""
echo "# Check for init_mm (init's memory descriptor):"
echo "sudo grep ' init_mm$' /proc/kallsyms"
echo ""
echo "# Look for swapper (another name for init_task):"
echo "sudo grep -i swapper /proc/kallsyms | grep -E ' [DB] '"
echo ""
echo "# Or check System.map differently:"
echo "grep -E ' [DB] init_task$' /boot/System.map-$(uname -r)"
echo ""
echo "The init_task should be a 'D' (data) symbol, not 't' or 'T' (text/code)"